sylius_ui:
    events:
        sylius.shop.product.index.box:
            blocks:
                content:
                    template: "products/_box.html.twig"
                    priority: 10

sylius_theme:
    sources:
        filesystem:
            directories:
                - "%kernel.project_dir%/themes"
