version: "3.4"
services:
    db:
        image: mysql:5.7
        ports:
            - "3306:3306"
        environment:
            MYSQL_USER: sylius
            MYSQL_PASSWORD: sylius
            MYSQL_DATABASE: sylius
            MYSQL_RANDOM_ROOT_PASSWORD: "yes"
        volumes:
            - ./etc/data:/var/lib/mysql
    
    php:
        build:
          context: ./etc/docker/php
        ports:
            - 8000:8000
        volumes:
            - .:/home/docker/workspace/sylius
            - ./etc/docker/php/symfony.ini:/etc/php/7.4/cli/conf.d/symfony.ini:ro

    js:
        build:
            context: ./etc/docker/js
            cache_from:
                - quay.io/sylius/php:latest
                - quay.io/sylius/nodejs:latest
                - quay.io/sylius/nginx:latest
        image: quay.io/sylius/nodejs:latest
        depends_on:
            - php
        environment:
            - GULP_ENV=dev
            - PHP_HOST=php
            - PHP_PORT=9000
        volumes:
            - .:/home/docker/workspace/sylius
        ports:
            - "35729:35729"
#    js:
#        build:
#            context: ./etc/docker/js
#        volumes:
#            - .:/home/docker/workspace/sylius
#        working_dir: /home/docker/workspace/sylius

    mailcatcher:
        image: zolweb/docker-mailcatcher:latest
        ports:
            - "1080:1080"
